### ISSUE TITLE
The url linked to from http://orgmode.org/worg/org-tutorials/ is broken

### ISSUE THREAD

**Issue by chrisportela** [jwiegley/newartisans#2]
http://newartisans.com/2007/08/using-org-mode-as-a-day-planner is supposed to point to your post on org-mode, and your list of posts has this on the last page, but that url does not work.

https://github.com/jwiegley/newartisans/blob/master/posts/2007-08-20-using-org-mode-as-a-day-planner.md

**Comment by jwiegley** [comment]
Thanks, it is fixed now.
